file:
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  uploadFolder: C://uploadFiles//
  #静态资源对外暴露的访问路径
  staticAccessPath: /file/**
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myweb
  mail:
    host: smtp.qq.com
    username: youdoufuz@qq.com
    password: lgsvnnlpiezicjfc
  cache:
    type: redis
  #    redis:
  #      time-to-live: 10000
  #      我怀疑配置类里的优先级更高
  redis:
    port: 6379
    host: localhost
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
mybatis-plus:
  configuration:
    #取消驼峰命名转化
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: mapper/*.xml
  type-aliases-package: com.myserver.Dao
server:
  servlet:
    context-path: /api
    session:
      timeout: 3600
      cookie:
        http-only: false
        path: /
  #      cookie:
  #        same-site: none
  port: 8080
logging:
  file:
    name: server.log
  logback:
    rollingpolicy:
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
